#ENC[AES256_GCM,data:I5QqlWE7GyTvs5Moyr/DAAdnN+BBTJ+h6Eb52RLAfakZwABvwEYFxHn2EiOe2PMwUvMANGAaV8i1oc2L,iv:pmkf5HtFYUaJ3HCJ4x/wiYwaeEfYK/Bx5fqtUOV35fM=,tag:3ooQgaM3UiTdWx0zU91C3A==,type:comment]
#
#ENC[AES256_GCM,data:E/dTd7Svxk5uEszs3cHApukKUUGBCvCCh+Pc1IiKkzhWMaoZdQmV,iv:0LstF58iYTZ1dKbZJVRzPnPSNDl4zcHCrYer8cN0wZ8=,tag:wbQOAJ/eQALh40fQr+xOLQ==,type:comment]
#ENC[AES256_GCM,data:v+ukZZTFD9bYiWASZNsvoDCt3fOI+8Pmm7TkU8jJKK1KLwcSPGzf6tBJwca8FqEaLK+N/49W,iv:cQhfmq1CoqSqNp/IGAfTsZtBCnCiPGryoeoMzkT6UYM=,tag:e6P7yLPXoPafPALxN57cng==,type:comment]
#ENC[AES256_GCM,data:OcVZu4aWtd6XCQW8+KTBnicYMT/LWz5SCafqZgGJzOVPF0DeXDE22pHi,iv:G2830y3ft1RSNtQnlSUpeuRvzC07K40sBLXM11EKFpM=,tag:QH/0rnhWLMqagmv4nfHHrQ==,type:comment]
#ENC[AES256_GCM,data:Zh949ML5ckIspiYcM6SnSbs1fyfWznEe5H1FD3cyzD9frETD9rlbnNNN2NkdPkTG3Dv3yAYjWFyVmOPPVJ8ylqgerQwI+Y+8Zg==,iv:nsaGdnTTg6czgfJnH8m5I2LsGq4++AHS2ZD076RdfIU=,tag:xWd2ACOj2yH/2+KaVNgG6Q==,type:comment]
#
#ENC[AES256_GCM,data:kqqzpgk3Ym3PaMBKkqd+SfKfOR2MKfZvatKpDa0QU0SlAMDIWgFBHSZXiLMd7yZAS1pOgHI5dWCppxORexhqXg6my/KTn7ScNyIOpg==,iv:dF6a1kJHvPL4gIUtryg/pN2xcDTdkh0Pwur+jK4IBgA=,tag:T1rjxoALDt5ncxX70XMnxg==,type:comment]
#ENC[AES256_GCM,data:KWd7tyVfz3JDXWKKwF0K7V0pDpmdQmpobmrpzei7l00Jir/s7Kafk2y+3SIxthhBAXdMoZJQm3jvxbeNzvDG+bdUlUJz7y+pkQ==,iv:KRoeAU4Bdfywx4T1JtyQ9mkz9hJOUAMhgtw/acX7snw=,tag:/isfqtKVI8CKuUpzTVmiCw==,type:comment]
#ENC[AES256_GCM,data:Qi6HxOZfJ9V9+somoSG1mStmV58lfUpF8ZhKCDmwgns8hMl/Xfg5YrcMmXDBQ8EaYmX0LQMxNWRsZ5OGUA==,iv:qpmW7QrORfS1E9rjn9LH+XZmRC8LPUzUeZbr871Vav4=,tag:8j5l4U7QFu0b0dCJBsuoqQ==,type:comment]
#
#ENC[AES256_GCM,data:9bCNMEeNCdb16fefhzCs6VS2KGm3nvgMtvVwxxgSTvPa/kRgfSddIOU593Y18lGPaCgj4BlXWkHXEkhOER5aSw4tPokrGQIjcA==,iv:XS1I0xS9fvvCtp21DiNutg10imngrZCy1yYhR8q9pfw=,tag:pVWJ6KrxPHgBqaan5iPEVA==,type:comment]
#ENC[AES256_GCM,data:C6+Zc6H3o7qeTdUIUVf1ZWU5ZGj/rPLO3tWeFTNM7a9rMyozBG/UjmPIPEnUB29vJ8+MdDIAY/NDWlBLZYuugw==,iv:cI/JUzFG7WfKFDe2Ro4yinIxBhVEUXru0SM01EyPHDw=,tag:002LGF16fV0ofN0d4nsMJQ==,type:comment]
#
#ENC[AES256_GCM,data:imeQlBUCoGbq6UXzEJw8RHH+J12OXwOvhMTD2svjHuUAMYJxFwyHlmllUHdnpMioy27M86jsxCJHaYeQ/5cCUrQuaDwSIA==,iv:eLDM8OsbS1LAd0tXhRqf0FSGeWacmkgjkm4+pEvtqIo=,tag:UsZnN1XQ1ReradA4xqdhHg==,type:comment]
#ENC[AES256_GCM,data:I7c7wSLG5jpJpwSnPcjDhCDZuAeGAcEcSU6NFPlPsTwYjrxDNJmKhTbdWfSu8C2PbyVPSPOJCu3F1V04P12j0Jzjp740sKsm,iv:jHjE500081A5fnN3nAxXfef9y3/Y9jrrWaiCbMOIu2c=,tag:RdYTgG2wuZghxla6uoAZBA==,type:comment]
#ENC[AES256_GCM,data:71zT3oOKmH8lB9AwZWPHXJeg2TbS9yyBN5/JGwFxl78YVFPFzzxrG4bJi2Y=,iv:Ux5yZI60zEAGk9v90ZakySgU/A7PHiUWTgKeL3tj0bQ=,tag:OlLnwWWBPvU4/gz/lHNEtA==,type:comment]
anthropic_api_key: ""
groq_api_key: ""
openai_api_key: ""
gateway_api_keys: ""
sops:
    gcp_kms:
        - created_at: "2026-08-26T15:42:24Z"
          enc: CiQA7gllWIkn09pjps0CFu5GJJwTYLviEEfCZLxa7H00v7LDj1cSSQAQNNqW88zf04PjcYz98LE9LgvayoqMeqGpkAT5HkbKy2C38ZW8XtWYxb4kHtq7LjO+sulhw4DcuhGyZJ3xJ89UEy7hvxooOhk=
          resource_id: projects/llm-gateway-mca01/locations/global/keyRings/llm-gateway-sops/cryptoKeys/secrets
    lastmodified: "2026-08-26T15:42:25Z"
    mac: ENC[AES256_GCM,data:XW9RsJwqYt7M7/i4pQF3VKHQFrGI8vTxmcTnKdZ9GzbcOPG+uY9ImEZFZ0ukFOWvgCvkiQwrMJmprl/7nsgy/251W5KOl8roN1HFlV0lcSASmMtra26bwk6HTztuhESvajPoAkIcMljXqXbu3YgzWwxqRq2dHeltyshaHC5tVY0=,iv:5GM2FsRfVbiGA9xqokcDmCSo10mNHsxx31+qunHFH8Y=,tag:X61PCCoSEV2wH//Z9ma/Eg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
